# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.SCRATCH = QtWidgets.QCheckBox(self.centralwidget)
        self.SCRATCH.setObjectName("SCRATCH")
        self.gridLayout.addWidget(self.SCRATCH, 5, 1, 1, 1)
        self.closeRemNeedPrac = QtWidgets.QCheckBox(self.centralwidget)
        self.closeRemNeedPrac.setObjectName("closeRemNeedPrac")
        self.gridLayout.addWidget(self.closeRemNeedPrac, 17, 7, 1, 1)
        self.CODECOMBAT = QtWidgets.QCheckBox(self.centralwidget)
        self.CODECOMBAT.setObjectName("CODECOMBAT")
        self.gridLayout.addWidget(self.CODECOMBAT, 5, 2, 1, 1)
        self.additionalNotesLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.additionalNotesLabel.setFont(font)
        self.additionalNotesLabel.setObjectName("additionalNotesLabel")
        self.gridLayout.addWidget(self.additionalNotesLabel, 15, 0, 1, 1)
        self.conceptClasses = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptClasses.setObjectName("conceptClasses")
        self.gridLayout.addWidget(self.conceptClasses, 11, 1, 1, 1)
        self.statementExcellent = QtWidgets.QCheckBox(self.centralwidget)
        self.statementExcellent.setObjectName("statementExcellent")
        self.gridLayout.addWidget(self.statementExcellent, 15, 9, 1, 1)
        self.REPLIT = QtWidgets.QCheckBox(self.centralwidget)
        self.REPLIT.setObjectName("REPLIT")
        self.gridLayout.addWidget(self.REPLIT, 4, 1, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout.addWidget(self.nameBox, 1, 0, 1, 2)
        self.conceptVariable = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptVariable.setObjectName("conceptVariable")
        self.gridLayout.addWidget(self.conceptVariable, 8, 1, 1, 1)
        self.dateWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.dateWidget.setGridVisible(True)
        self.dateWidget.setObjectName("dateWidget")
        self.gridLayout.addWidget(self.dateWidget, 2, 7, 7, 3)
        self.closeRemLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.closeRemLabel.setFont(font)
        self.closeRemLabel.setObjectName("closeRemLabel")
        self.gridLayout.addWidget(self.closeRemLabel, 16, 7, 1, 1)
        self.conceptDicts = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptDicts.setObjectName("conceptDicts")
        self.gridLayout.addWidget(self.conceptDicts, 9, 1, 1, 1)
        self.platformsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.platformsLabel.setFont(font)
        self.platformsLabel.setObjectName("platformsLabel")
        self.gridLayout.addWidget(self.platformsLabel, 3, 0, 1, 1)
        self.conceptLists = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptLists.setObjectName("conceptLists")
        self.gridLayout.addWidget(self.conceptLists, 11, 0, 1, 1)
        self.statementGood = QtWidgets.QCheckBox(self.centralwidget)
        self.statementGood.setObjectName("statementGood")
        self.gridLayout.addWidget(self.statementGood, 15, 8, 1, 1)
        self.additionalNotesTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.additionalNotesTextBox.setObjectName("additionalNotesTextBox")
        self.gridLayout.addWidget(self.additionalNotesTextBox, 17, 0, 2, 2)
        self.conceptMultiFunc = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptMultiFunc.setObjectName("conceptMultiFunc")
        self.gridLayout.addWidget(self.conceptMultiFunc, 13, 1, 1, 1)
        self.conceptFunctions = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptFunctions.setObjectName("conceptFunctions")
        self.gridLayout.addWidget(self.conceptFunctions, 9, 2, 1, 1)
        self.TRINKET = QtWidgets.QCheckBox(self.centralwidget)
        self.TRINKET.setObjectName("TRINKET")
        self.gridLayout.addWidget(self.TRINKET, 4, 2, 1, 1)
        self.HACKERRANK = QtWidgets.QCheckBox(self.centralwidget)
        self.HACKERRANK.setObjectName("HACKERRANK")
        self.gridLayout.addWidget(self.HACKERRANK, 6, 0, 1, 1)
        self.conceptsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.conceptsLabel.setFont(font)
        self.conceptsLabel.setObjectName("conceptsLabel")
        self.gridLayout.addWidget(self.conceptsLabel, 7, 0, 1, 1)
        self.conceptDataStruct = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptDataStruct.setObjectName("conceptDataStruct")
        self.gridLayout.addWidget(self.conceptDataStruct, 13, 0, 1, 1)
        self.conceptConditionals = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptConditionals.setObjectName("conceptConditionals")
        self.gridLayout.addWidget(self.conceptConditionals, 12, 1, 1, 1)
        self.conceptAlgo = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptAlgo.setObjectName("conceptAlgo")
        self.gridLayout.addWidget(self.conceptAlgo, 12, 2, 1, 1)
        self.projectsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.projectsLabel.setFont(font)
        self.projectsLabel.setObjectName("projectsLabel")
        self.gridLayout.addWidget(self.projectsLabel, 9, 7, 1, 1)
        self.conceptString = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptString.setObjectName("conceptString")
        self.gridLayout.addWidget(self.conceptString, 8, 0, 1, 1)
        self.conceptObjects = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptObjects.setObjectName("conceptObjects")
        self.gridLayout.addWidget(self.conceptObjects, 11, 2, 1, 1)
        self.conceptDatatypes = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptDatatypes.setObjectName("conceptDatatypes")
        self.gridLayout.addWidget(self.conceptDatatypes, 8, 2, 1, 1)
        self.projectTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.projectTextBox.setObjectName("projectTextBox")
        self.gridLayout.addWidget(self.projectTextBox, 12, 7, 2, 3)
        self.statementDecent = QtWidgets.QCheckBox(self.centralwidget)
        self.statementDecent.setObjectName("statementDecent")
        self.gridLayout.addWidget(self.statementDecent, 15, 7, 1, 1)
        self.CHECKIO = QtWidgets.QCheckBox(self.centralwidget)
        self.CHECKIO.setObjectName("CHECKIO")
        self.gridLayout.addWidget(self.CHECKIO, 5, 0, 1, 1)
        self.codecademyBox = QtWidgets.QCheckBox(self.centralwidget)
        self.codecademyBox.setObjectName("codecademyBox")
        self.gridLayout.addWidget(self.codecademyBox, 4, 0, 1, 1)
        self.conceptLambdas = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptLambdas.setObjectName("conceptLambdas")
        self.gridLayout.addWidget(self.conceptLambdas, 12, 0, 1, 1)
        self.conceptLoops = QtWidgets.QCheckBox(self.centralwidget)
        self.conceptLoops.setObjectName("conceptLoops")
        self.gridLayout.addWidget(self.conceptLoops, 9, 0, 1, 1)
        self.statementLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.statementLabel.setFont(font)
        self.statementLabel.setObjectName("statementLabel")
        self.gridLayout.addWidget(self.statementLabel, 14, 7, 1, 1)
        self.projectCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.projectCheckbox.setObjectName("projectCheckbox")
        self.gridLayout.addWidget(self.projectCheckbox, 11, 7, 1, 1)
        self.closeRemContPrac = QtWidgets.QCheckBox(self.centralwidget)
        self.closeRemContPrac.setObjectName("closeRemContPrac")
        self.gridLayout.addWidget(self.closeRemContPrac, 17, 8, 1, 1)
        self.closeRemKeepPrac = QtWidgets.QCheckBox(self.centralwidget)
        self.closeRemKeepPrac.setObjectName("closeRemKeepPrac")
        self.gridLayout.addWidget(self.closeRemKeepPrac, 17, 9, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 19, 9, 1, 1)
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 19, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameLabel.setText(_translate("MainWindow", "NAME:"))
        self.SCRATCH.setText(_translate("MainWindow", "SCRATCH"))
        self.closeRemNeedPrac.setText(_translate("MainWindow", "NEEDS PRACTICE"))
        self.CODECOMBAT.setText(_translate("MainWindow", "CODE COMBAT"))
        self.additionalNotesLabel.setText(_translate("MainWindow", "ADDITIONAL NOTES:"))
        self.conceptClasses.setText(_translate("MainWindow", "CLASSES"))
        self.statementExcellent.setText(_translate("MainWindow", "EXCELLENT"))
        self.REPLIT.setText(_translate("MainWindow", "REPL.IT"))
        self.nameBox.setPlaceholderText(_translate("MainWindow", "Enter Student Name"))
        self.conceptVariable.setText(_translate("MainWindow", "VARIABLES"))
        self.dateWidget.setStatusTip(_translate("MainWindow", "Select Date"))
        self.closeRemLabel.setText(_translate("MainWindow", "CLOSING REMARKS:"))
        self.conceptDicts.setText(_translate("MainWindow", "DICTIONARIES"))
        self.platformsLabel.setText(_translate("MainWindow", "PLATFORMS USED:"))
        self.conceptLists.setText(_translate("MainWindow", "LISTS"))
        self.statementGood.setText(_translate("MainWindow", "GOOD"))
        self.additionalNotesTextBox.setPlaceholderText(_translate("MainWindow", "Additional Notes Here"))
        self.conceptMultiFunc.setText(_translate("MainWindow", "MULTI FUNCTION PROG"))
        self.conceptFunctions.setText(_translate("MainWindow", "FUNCTIONS"))
        self.TRINKET.setText(_translate("MainWindow", "TRINKET"))
        self.HACKERRANK.setText(_translate("MainWindow", "HACKER RANK"))
        self.conceptsLabel.setText(_translate("MainWindow", "CONCEPTS COVERED:"))
        self.conceptDataStruct.setText(_translate("MainWindow", "DATA STRUCTURES"))
        self.conceptConditionals.setText(_translate("MainWindow", "CONDITIONALS"))
        self.conceptAlgo.setText(_translate("MainWindow", "ALGORITHMS"))
        self.projectsLabel.setText(_translate("MainWindow", "PROJECTS:"))
        self.conceptString.setText(_translate("MainWindow", "STRINGS"))
        self.conceptObjects.setText(_translate("MainWindow", "OBJECTS"))
        self.conceptDatatypes.setText(_translate("MainWindow", "DATATYPES"))
        self.projectTextBox.setPlaceholderText(_translate("MainWindow", "Name of Project"))
        self.statementDecent.setText(_translate("MainWindow", "DECENT"))
        self.CHECKIO.setText(_translate("MainWindow", "CHECKIO.ORG"))
        self.codecademyBox.setText(_translate("MainWindow", "CODECADEMY"))
        self.conceptLambdas.setText(_translate("MainWindow", "ANON FUNCS"))
        self.conceptLoops.setText(_translate("MainWindow", "LOOPS"))
        self.statementLabel.setText(_translate("MainWindow", "STATEMENTS:"))
        self.projectCheckbox.setText(_translate("MainWindow", "CHECK BOX FOR PROJECT"))
        self.closeRemContPrac.setText(_translate("MainWindow", "CONTINUE PRACTICE"))
        self.closeRemKeepPrac.setText(_translate("MainWindow", "KEEP UP WORK"))
        self.cancelButton.setText(_translate("MainWindow", "CANCEL"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExport.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
