

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 20, 321, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.platformsLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.platformsLabel.setFont(font)
        self.platformsLabel.setObjectName("platformsLabel")
        self.gridLayout.addWidget(self.platformsLabel, 0, 0, 1, 1)
        self.codecademyBox = QtWidgets.QCheckBox(self.frame)
        self.codecademyBox.setObjectName("codecademyBox")
        self.gridLayout.addWidget(self.codecademyBox, 1, 0, 1, 1)
        self.REPLIT = QtWidgets.QCheckBox(self.frame)
        self.REPLIT.setObjectName("REPLIT")
        self.gridLayout.addWidget(self.REPLIT, 1, 1, 1, 1)
        self.TRINKET = QtWidgets.QCheckBox(self.frame)
        self.TRINKET.setObjectName("TRINKET")
        self.gridLayout.addWidget(self.TRINKET, 1, 2, 1, 1)
        self.CHECKIO = QtWidgets.QCheckBox(self.frame)
        self.CHECKIO.setObjectName("CHECKIO")
        self.gridLayout.addWidget(self.CHECKIO, 2, 0, 1, 1)
        self.SCRATCH = QtWidgets.QCheckBox(self.frame)
        self.SCRATCH.setObjectName("SCRATCH")
        self.gridLayout.addWidget(self.SCRATCH, 2, 1, 1, 1)
        self.CODECOMBAT = QtWidgets.QCheckBox(self.frame)
        self.CODECOMBAT.setObjectName("CODECOMBAT")
        self.gridLayout.addWidget(self.CODECOMBAT, 2, 2, 1, 1)
        self.HACKERRANK = QtWidgets.QCheckBox(self.frame)
        self.HACKERRANK.setObjectName("HACKERRANK")
        self.gridLayout.addWidget(self.HACKERRANK, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 150, 29))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nameLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(self.frame_2)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout_2.addWidget(self.nameBox, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 120, 321, 118))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.conceptsLabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.conceptsLabel.setFont(font)
        self.conceptsLabel.setObjectName("conceptsLabel")
        self.gridLayout_3.addWidget(self.conceptsLabel, 0, 0, 1, 1)
        self.conceptString = QtWidgets.QCheckBox(self.frame_3)
        self.conceptString.setObjectName("conceptString")
        self.gridLayout_3.addWidget(self.conceptString, 1, 0, 1, 1)
        self.conceptVariable = QtWidgets.QCheckBox(self.frame_3)
        self.conceptVariable.setObjectName("conceptVariable")
        self.gridLayout_3.addWidget(self.conceptVariable, 1, 1, 1, 1)
        self.conceptDatatypes = QtWidgets.QCheckBox(self.frame_3)
        self.conceptDatatypes.setObjectName("conceptDatatypes")
        self.gridLayout_3.addWidget(self.conceptDatatypes, 1, 2, 1, 1)
        self.conceptLoops = QtWidgets.QCheckBox(self.frame_3)
        self.conceptLoops.setObjectName("conceptLoops")
        self.gridLayout_3.addWidget(self.conceptLoops, 2, 0, 1, 1)
        self.conceptDicts = QtWidgets.QCheckBox(self.frame_3)
        self.conceptDicts.setObjectName("conceptDicts")
        self.gridLayout_3.addWidget(self.conceptDicts, 2, 1, 1, 1)
        self.conceptFunctions = QtWidgets.QCheckBox(self.frame_3)
        self.conceptFunctions.setObjectName("conceptFunctions")
        self.gridLayout_3.addWidget(self.conceptFunctions, 2, 2, 1, 1)
        self.conceptLists = QtWidgets.QCheckBox(self.frame_3)
        self.conceptLists.setObjectName("conceptLists")
        self.gridLayout_3.addWidget(self.conceptLists, 3, 0, 1, 1)
        self.conceptClasses = QtWidgets.QCheckBox(self.frame_3)
        self.conceptClasses.setObjectName("conceptClasses")
        self.gridLayout_3.addWidget(self.conceptClasses, 3, 1, 1, 1)
        self.conceptObjects = QtWidgets.QCheckBox(self.frame_3)
        self.conceptObjects.setObjectName("conceptObjects")
        self.gridLayout_3.addWidget(self.conceptObjects, 3, 2, 1, 1)
        self.conceptLambdas = QtWidgets.QCheckBox(self.frame_3)
        self.conceptLambdas.setObjectName("conceptLambdas")
        self.gridLayout_3.addWidget(self.conceptLambdas, 4, 0, 1, 1)
        self.conceptConditionals = QtWidgets.QCheckBox(self.frame_3)
        self.conceptConditionals.setObjectName("conceptConditionals")
        self.gridLayout_3.addWidget(self.conceptConditionals, 4, 1, 1, 1)
        self.conceptAlgo = QtWidgets.QCheckBox(self.frame_3)
        self.conceptAlgo.setObjectName("conceptAlgo")
        self.gridLayout_3.addWidget(self.conceptAlgo, 4, 2, 1, 1)
        self.conceptDataStruct = QtWidgets.QCheckBox(self.frame_3)
        self.conceptDataStruct.setObjectName("conceptDataStruct")
        self.gridLayout_3.addWidget(self.conceptDataStruct, 5, 0, 1, 1)
        self.conceptMultiFunc = QtWidgets.QCheckBox(self.frame_3)
        self.conceptMultiFunc.setObjectName("conceptMultiFunc")
        self.gridLayout_3.addWidget(self.conceptMultiFunc, 5, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(340, 140, 270, 161))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.additionalNotesTextBox = QtWidgets.QTextEdit(self.frame_4)
        self.additionalNotesTextBox.setObjectName("additionalNotesTextBox")
        self.gridLayout_4.addWidget(self.additionalNotesTextBox, 1, 0, 1, 1)
        self.additionalNotesLabel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.additionalNotesLabel.setFont(font)
        self.additionalNotesLabel.setObjectName("additionalNotesLabel")
        self.gridLayout_4.addWidget(self.additionalNotesLabel, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(340, 20, 270, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.projectsLabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.projectsLabel.setFont(font)
        self.projectsLabel.setObjectName("projectsLabel")
        self.gridLayout_5.addWidget(self.projectsLabel, 0, 0, 1, 1)
        self.projectCheckbox = QtWidgets.QCheckBox(self.frame_5)
        self.projectCheckbox.setObjectName("projectCheckbox")
        self.gridLayout_5.addWidget(self.projectCheckbox, 1, 0, 1, 1)
        self.projectTextBox = QtWidgets.QTextEdit(self.frame_5)
        self.projectTextBox.setObjectName("projectTextBox")
        self.gridLayout_5.addWidget(self.projectTextBox, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(0, 240, 321, 101))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.statementLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.statementLabel.setFont(font)
        self.statementLabel.setObjectName("statementLabel")
        self.gridLayout_6.addWidget(self.statementLabel, 0, 0, 1, 1)
        self.statementDecent = QtWidgets.QCheckBox(self.frame_6)
        self.statementDecent.setObjectName("statementDecent")
        self.gridLayout_6.addWidget(self.statementDecent, 1, 0, 1, 1)
        self.statementGood = QtWidgets.QCheckBox(self.frame_6)
        self.statementGood.setObjectName("statementGood")
        self.gridLayout_6.addWidget(self.statementGood, 1, 1, 1, 1)
        self.statementExcellent = QtWidgets.QCheckBox(self.frame_6)
        self.statementExcellent.setObjectName("statementExcellent")
        self.gridLayout_6.addWidget(self.statementExcellent, 1, 2, 1, 1)
        self.closeRemLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.closeRemLabel.setFont(font)
        self.closeRemLabel.setObjectName("closeRemLabel")
        self.gridLayout_6.addWidget(self.closeRemLabel, 2, 0, 1, 1)
        self.closeRemNeedPrac = QtWidgets.QCheckBox(self.frame_6)
        self.closeRemNeedPrac.setObjectName("closeRemNeedPrac")
        self.gridLayout_6.addWidget(self.closeRemNeedPrac, 3, 0, 1, 1)
        self.closeRemContPrac = QtWidgets.QCheckBox(self.frame_6)
        self.closeRemContPrac.setObjectName("closeRemContPrac")
        self.gridLayout_6.addWidget(self.closeRemContPrac, 3, 1, 1, 1)
        self.closeRemKeepPrac = QtWidgets.QCheckBox(self.frame_6)
        self.closeRemKeepPrac.setObjectName("closeRemKeepPrac")
        self.gridLayout_6.addWidget(self.closeRemKeepPrac, 3, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(429, 400, 181, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.okButton = QtWidgets.QPushButton(self.frame_7)
        self.okButton.setObjectName("okButton")
        self.gridLayout_7.addWidget(self.okButton, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.frame_7)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_7.addWidget(self.cancelButton, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.platformsLabel.setText(_translate("MainWindow", "PLATFORMS USED:"))
        self.codecademyBox.setText(_translate("MainWindow", "CODECADEMY"))
        self.REPLIT.setText(_translate("MainWindow", "REPL.IT"))
        self.TRINKET.setText(_translate("MainWindow", "TRINKET"))
        self.CHECKIO.setText(_translate("MainWindow", "CHECKIO.ORG"))
        self.SCRATCH.setText(_translate("MainWindow", "SCRATCH"))
        self.CODECOMBAT.setText(_translate("MainWindow", "CODE COMBAT"))
        self.HACKERRANK.setText(_translate("MainWindow", "HACKER RANK"))
        self.nameLabel.setText(_translate("MainWindow", "NAME:"))
        self.nameBox.setPlaceholderText(_translate("MainWindow", "Enter Student Name"))
        self.conceptsLabel.setText(_translate("MainWindow", "CONCEPTS COVERED:"))
        self.conceptString.setText(_translate("MainWindow", "STRINGS"))
        self.conceptVariable.setText(_translate("MainWindow", "VARIABLES"))
        self.conceptDatatypes.setText(_translate("MainWindow", "DATATYPES"))
        self.conceptLoops.setText(_translate("MainWindow", "LOOPS"))
        self.conceptDicts.setText(_translate("MainWindow", "DICTIONARIES"))
        self.conceptFunctions.setText(_translate("MainWindow", "FUNCTIONS"))
        self.conceptLists.setText(_translate("MainWindow", "LISTS"))
        self.conceptClasses.setText(_translate("MainWindow", "CLASSES"))
        self.conceptObjects.setText(_translate("MainWindow", "OBJECTS"))
        self.conceptLambdas.setText(_translate("MainWindow", "ANON FUNCS"))
        self.conceptConditionals.setText(_translate("MainWindow", "CONDITIONALS"))
        self.conceptAlgo.setText(_translate("MainWindow", "ALGORITHMS"))
        self.conceptDataStruct.setText(_translate("MainWindow", "DATA STRUCTURES"))
        self.conceptMultiFunc.setText(_translate("MainWindow", "MULTI FUNCTION PROG"))
        self.additionalNotesTextBox.setPlaceholderText(_translate("MainWindow", "Additional Notes Here"))
        self.additionalNotesLabel.setText(_translate("MainWindow", "ADDITIONAL NOTES:"))
        self.projectsLabel.setText(_translate("MainWindow", "PROJECTS:"))
        self.projectCheckbox.setText(_translate("MainWindow", "CHECK BOX FOR PROJECT"))
        self.projectTextBox.setPlaceholderText(_translate("MainWindow", "Name of Project"))
        self.statementLabel.setText(_translate("MainWindow", "STATEMENTS:"))
        self.statementDecent.setText(_translate("MainWindow", "DECENT"))
        self.statementGood.setText(_translate("MainWindow", "GOOD"))
        self.statementExcellent.setText(_translate("MainWindow", "EXCELLENT"))
        self.closeRemLabel.setText(_translate("MainWindow", "CLOSING REMARKS:"))
        self.closeRemNeedPrac.setText(_translate("MainWindow", "NEEDS PRACTICE"))
        self.closeRemContPrac.setText(_translate("MainWindow", "CONTINUE PRACTICE"))
        self.closeRemKeepPrac.setText(_translate("MainWindow", "KEEP UP WORK"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.cancelButton.setText(_translate("MainWindow", "CANCEL"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExport.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
